### ISSUE TITLE
Gaya Penulisan Kode dan Menggunakan Sintaks Modul EcmaScript

### ISSUE THREAD

**Issue by jefrydco** [fransiscusrolandamalau/webinar-spa-vue#1]
Hi Mas Fransiscus, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Fransiscus.

Mas juga sudah menggunakan Vue CLI dan kerangka kerja CSS Tailwind untuk aplikasi pencari teks pada video YouTube ini. Luar biasa Mas!

Saya ada 2 saran kecil Mas

1. Gaya Penulisan Kode
Pada berkas `src/components/ApiSearch.vue` pada baris 68-71 berikut:

https://github.com/fransiscusrolandamalau/webinar-spa-vue/blob/1eee6af53c26989b4d1f7923c43f12a806120045/src/components/ApiSearch.vue#L68-L71

sepertinya kodenya belum terformat dengan baik. Saya rasa hal tersebut dikarenakan perbaikan otomatis oleh Eslint atau Prettier ya Mas.

2. Menggunakan Sintaks Modul EcmaScript untuk Impor Paket
Masih pada berkas `src/components/ApiSearch.vue` pada baris ke 104 berikut:

https://github.com/fransiscusrolandamalau/webinar-spa-vue/blob/1eee6af53c26989b4d1f7923c43f12a806120045/src/components/ApiSearch.vue#L104-L105

Mas menggunakan fungsi `require` (sintaks CommonJS) untuk mengimpor paket NPM pDebounce. Saya sarankan Mas untuk selalu menggunakan sintaks EcmaScript untuk mengimpor paket NPM. Kurang lebih kode di atas akan menjadi seperti berikut:

```javascript
import pDebounce from 'p-debounce'
```

Menggunakan sintaks ES kode kita akan sedikit lebih efektif ketika proses _build_ oleh Webpack Mas karena Webpack dapat mengeliminasi kode-kode yg memang tidak digunakan.

Lebih lanjut mengenai perbandingan sintaks CommonJS dengan ES dapat Mas baca pada tautan berikut, [StackOverflow - Difference Between require and Import](https://stackoverflow.com/a/46677972).

Oiya saya juga menyarankan untuk menambahkan jarak antara bagian impor paket NPM dengan `export default`. Hal tersebut akan sangat membantu untuk keterbacaan kode.

Semangat Mas! 😄

**Comment by fransiscusrolandamalau** [comment]
Selamat malam mas Jefry, terima kasih banyak telah mengoreksi hasil proyek
saya serta memberika sarannya,  untuk kedepannya akan saya tingkatkan lagi
mas, terima kasih mas

**Comment by jefrydco** [comment]
Terima kasih kembali Mas. Saya akan membiarkan isu ini terbuka ya Mas, nanti jika Mas ada waktu dan berkenan untuk memperbaiki beberapa saran di atas, Mas dapat menutup isu ini. Semangat selalu Mas! 😄

**Comment by fransiscusrolandamalau** [comment]
oke siap mas

**Comment by fransiscusrolandamalau** [comment]
sudah saya perbaiki ya Mas dari saran yang Mas berikan, terima kasih
